# Generated by Django 2.0.7 on 2018-08-02 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('level_total', models.IntegerField()),
                ('id_host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='invitation',
            fields=[
                ('id_invit', models.AutoField(primary_key=True, serialize=False)),
                ('accepted', models.BooleanField(default=0)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myGroceries.event')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='invitProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_invit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myGroceries.invitation')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='invitprod',
            name='id_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myGroceries.product'),
        ),
    ]
