# Generated by Django 2.0.7 on 2018-08-03 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myGroceries', '0002_auto_20180803_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='level_total',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='id_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myGroceries.Event'),
        ),
        migrations.AlterField(
            model_name='invitprod',
            name='id_invit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myGroceries.Invitation'),
        ),
        migrations.AlterField(
            model_name='invitprod',
            name='id_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myGroceries.Product'),
        ),
    ]
