# Generated by Django 2.0.7 on 2018-08-06 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myGroceries', '0005_auto_20180803_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='id_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myGroceries.Event'),
        ),
        migrations.AlterField(
            model_name='invitprod',
            name='id_invit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myGroceries.Invitation'),
        ),
        migrations.AlterField(
            model_name='invitprod',
            name='id_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myGroceries.Product'),
        ),
    ]
